### ISSUE TITLE
Question about back porting

### ISSUE THREAD

**Issue by michaelrice** [nerdErg/swagger4jaxrs#1]
Do you know what it would take to make this work on older grails like 2.1.1 with jaxrs 0.6?

**Comment by aruizca** [comment]
Hi Michael,

I am not sure what the changes are from jaxrs 0.6 to 0.8 which is the one I am using. I will create a branch with those dependencies and maybe you can try it for me :-)

The grails version should not be a problem.

Cheers,
Angel.

**Comment by michaelrice** [comment]
Wonderful! Yes I will be happy to test it.

**Comment by michaelrice** [comment]
So I have a working branch already. This is amazing. Ill post up what did shortly. Very few changes were needed.

**Comment by aruizca** [comment]
Cool!
We are talking to the owner of the jaxrs plugin, because we think the Grails 2.2 restriction is not required. Both his plugin and mine should work in Grails 2.x+ IMO. I'll keep you posted. Hopefully we will be able to publish a final version that you can use and maybe upgrade your jaxrs dependency too :+1:
